config/routes.rb
Rails.application.routes.draw do
  get 'users/downgrade', to: 'users#downgrade'

  post 'users/downgrade', to: 'users#perform_downgrade'

  devise_for :users

  resources :users

  resources :wikis do
    resources :collaborators
  end

  resources :charges, only: %i[new create]

  root 'wikis#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
  has_many :wikis
  has_many :coloborators
  has_many :shared_wikis, through: :collaborations, source: :wiki

  after_initialize :init
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  enum role: %i[standard premium admin]

  def init
    self.role ||= 0 # will set the default value only if it's nil
  end
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user, optional: true
  has_many :collaborators
  has_many :users, through: :collaborators

  # lets you filter public wikis
  def public?
    !private?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  # Set the default charge amount constant
  CHARGE_AMOUNT = 1500

  def create
    begin
      # Creates a Stripe Customer object, for associating
      # with the charge
      customer = Stripe::Customer.create(
        email: current_user.email,
        card: params[:stripeToken]
      )

      # Where the real magic happens
      charge = Stripe::Charge.create(
        customer: customer.id, # Note -- this is NOT the user_id in your app
        amount: CHARGE_AMOUNT,
        description: "BigMoney Membership - #{current_user.email}",
        currency: 'usd'
      )

      # Update user to premium role
      current_user.update_attribute(:role, 'premium')

      # Save the user and flash a message to them
      if current_user.save!
        flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
        redirect_to wikis_path(current_user) # or wherever
      end

    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
    end
  end

  def new
    @stripe_btn_data = {
      key: Rails.configuration.stripe[:publishable_key].to_s,
      description: "BigMoney Membership - #{current_user.email}",
      amount: CHARGE_AMOUNT
    }
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_wiki, only: %i[index create destroy]

  def index
    @users = User.all
  end

  def new
    @collaborator = Collaborator.new
    @user = User.all
    @wiki = Wiki.find(params[:wiki_id])
  end

  def show
    @collaborator = Collaborator.find(params[:wiki_id])
  end

  def create
    collaborator = Collaborator.new(wiki_id: @wiki.id, user_id: params[:user_id])

    if collaborator.save
      flash[:success] = 'Collaborator added to wiki.'
      redirect_to wiki_collaborators_path(@wiki)
    else
      flash[:error] = 'There was an error deleting this collaborator. Please try again.'
    end
  end

  def destroy
    collaborator = Collaborator.find_by(user_id: params[:user_id], wiki_id: @wiki.id)

    if collaborator.delete
      flash[:success] = 'Collaborator removed from wiki.'
      redirect_to wiki_collaborators_path(@wiki)
    else
      flash[:error] = 'There was an error deleting this collaborator. Please try again.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def wiki_params
    params.reaquire(:wiki).permit(:collaborators)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new; end

  def downgrade; end

  def perform_downgrade
    if downgrade_current_user
      make_wikis_public
      flash[:notice] = "Your account has been downgraded, #{current_user.email}!"
      redirect_to wikis_path(current_user) # or wherever
    end
  end

  private

  def downgrade_current_user
    current_user.update_attribute(:role, 'standard')
    current_user.save!
  end

  def make_wikis_public
    current_user.wikis.update_all(private: false)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :set_wiki, only: %i[show edit update destroy]
  skip_before_action :verify_authenticity_token
  # GET /wikis
  # GET /wikis.json
  def index
    @wikis = policy_scope(Wiki)
  end

  # GET /wikis/1
  # GET /wikis/1.json
  def show
    @wiki = Wiki.find(params[:id])
  end

  # GET /wikis/new
  def new
    @wiki = Wiki.new
  end

  # GET /wikis/1/edit
  def edit
    @wiki = Wiki.find(params[:id])
  end

  # POST /wikis
  # POST /wikis.json
  def create
    @wiki = current_user.wikis.new(wiki_params)

    respond_to do |format|
      if @wiki.save
        format.html { redirect_to @wiki, notice: 'Wiki was successfully created.' }
        format.json { render :show, status: :created, location: @wiki }
      else
        format.html { render :new }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wikis/1
  # PATCH/PUT /wikis/1.json
  def update
    respond_to do |format|
      if @wiki.update(wiki_params)
        authorize @wiki
        format.html { redirect_to @wiki, notice: 'Wiki was successfully updated.' }
        format.json { render :show, status: :ok, location: @wiki }
      else
        format.html { render :edit }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wikis/1
  # DELETE /wikis/1.json
  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = 'There was an error deleting the question.'
      render :show
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_wiki
    @wiki = Wiki.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: '_blank' },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaobrators_helper.rb
module CollaobratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>

  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborators/create.html.erb
<h1>Collaobrators#create</h1>
<%= render 'form', collaobrator: @collaobrator %>
<p>Find me in app/views/collaobrators/create.html.erb</p>

app/views/collaborators/destroy.html.erb
<h1>Collaobrators#destroy</h1>
<p>Find me in app/views/collaobrators/destroy.html.erb</p>

app/views/collaborators/index.html.erb
  <table class="table table-striped">
    <caption>Add collaborators to the wiki (All users)</caption>
    <thead>
      <tr>
        <th>Email</th>
        <th>Give Access</th>
        <th>Remove Access</th>
      </tr>
    </thead>
    <tbody>
      <% User.all.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td>
            <div>
              <td>
                <% if @wiki.users.exclude?(user) %>
                  <%= button_to "Add as Collaborator", wiki_collaborators_path(@wiki, user), method: :create, params: { user_id: user.id } %>
                <% end %>
              </td>
            </div>
            <div>
              <td>
                <% if @wiki.users.include?(user) %>
                  <%= button_to "Delete Collaborator", wiki_collaborator_path(@wiki, user), method: :delete, params: { user_id: user.id } %>
                <% end %>
              </td>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
  <%= link_to 'Back to Wikis index', wikis_path, method: :get %>
  </div>

app/views/collaborators/new.html.erb
<h1>Collaobrators#new</h1>

app/views/collaborators/show.html.erb
<h1>Collaborations#show</h1>
<p>Find me in app/views/collaborations/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grayapedia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if user_signed_in? %>
        Signed in as: <strong><%= current_user.email %></strong> |
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
        <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>

      <br>

      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/users/downgrade.html.erb
<h1>Downgrade your account</h1>

<%= link_to 'Down Grade your account', users_downgrade_path, method: :post %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/wikis/_form.html.erb
<%= form_with(model: @wiki, local: true) do |form| %>

  <% if @wiki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wiki.errors.count, "error") %> prohibited this wiki from being saved:</h2>
      <ul>
      <% wiki.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="form-group"">
    <p>Title:</p>
    <% form.label :title %>
    <%= form.text_field :title %> </div>
  <div class="">
    <p>Body:</p>
    <% form.label :body %>
    <%= form.text_area :body %>
  </div>
  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group"">
      <%= check_box 'wiki', :private, {}, 'true', 'false' %> Private wiki
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/wikis/edit.html.erb
<h1>Editing Wiki</h1>

<%= render 'form', wiki: @wiki %>

<%= link_to 'Show', @wiki %> |
<%= link_to 'Back', wikis_path %>

app/views/wikis/index.html.erb
<h1>Wikis</h1>

<table class="table table-striped">
  <tbody>
    <% @wikis.each do |wiki| %>
      <tr>
        <td><%= wiki.title %></td>
        <td><%= link_to 'Show', wiki %></td>
        <% if policy(wiki).update? %>
        <td><%= link_to 'Edit', edit_wiki_path(wiki) %></td>
        <td><%= link_to 'Destroy', wiki, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wiki', new_wiki_path %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<%= render 'form', wiki: @wiki %>

<%= link_to 'Back', wikis_path %>

app/views/wikis/show.html.erb
<div class="container">


<h2>Titlle</h2>
<div class="mktitle">
<%= @wiki.title %>
</div>
<h2>Body</h2>
<div class="mkbody">
<%= markdown(@wiki.body) %>
</div>

<% if policy(@wiki).update? %>
<%= link_to 'Edit', edit_wiki_path(@wiki) %>
<%= link_to_if current_user == @wiki.user, "Collaborators", wiki_collaborators_path(@wiki) %>
<% end %>

<%= link_to 'Back', wikis_path %>

</div>